name: Release
run-name: Release to prod from ${{ inputs.source-environment }}${{ inputs.source-environment == 'dev' && ' ⚠️ (skipped stage)' || '' }}

on:
    workflow_dispatch:
        inputs:
            source-environment:
                description: |
                    ⚠️ Critical Use Only:
                    This workflow promotes the stage image by default.
                    Choose dev image only if skipping staging is required in urgent cases.
                required: true
                type: choice
                default: stage
                options: [dev, stage]


jobs:

    echo-world:
        runs-on: ubuntu-latest
        steps:
            - name: 'hello'
              run: echo 'hello'

    approvals:
        needs: [echo-world]
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: successfully approved
              run: |
                echo "successfully approved and proceeding to deplo to prod"


    deploy:
        runs-on: ubuntu-latest
        needs: [echo-world, approvals]

        steps:
            - name: successfully approved
              run: |
                echo "successfully approved and proceeding to deplo to prod"



# name: Release
# run-name: Release to prod from ${{ inputs.source-environment }}${{ inputs.source-environment == 'dev' && ' ⚠️ (not deployed to stage)' || '' }}

# on:
#     workflow_dispatch:
#         inputs:
#             source-environment:
#                 description: |
#                     Select the environment tag to promote to production.
#                     - `stage`: Default. Promote image previously deployed to stage.
#                     - `dev`: ⚠️ Not deployed to stage. Use only in critical cases with senior approval.
#                 required: true
#                 type: choice
#                 default: stage
#                 options: [dev, stage]


# jobs:
#     echo-world:
#         runs-on: ubuntu-latest
#         steps:
#             - name: 'hello'
#               run: echo 'hello'

